### ISSUE TITLE
How to remove origin rails directory?

### ISSUE THREAD

**Issue by fifiteen82726** [tadast/sublime-rails-snippets#23]
Housekeeping

:warning: You will need to do some housekeeping after installing it from Package Control. First of all, remove the original Rails directory (see Backup). Then quit Sublime and delete Sublime's session cache.

I didn't get it, how to find my original rails directory? is it existing in my sublime folder?

**Comment by tadast** [comment]
Oh, that must have been a leftover from Sublime Text 2. If that's what you're using there will be a default `Rails` directory that you need to remove. In ST3 I couldn't find where it's located, if you find out, please let me know. Otherwise, you don't have to do anything, you'll just see two suggestions for some snippets - one form an outdated standard ST package, and one from this one.

**Comment by fifiteen82726** [comment]
Thanks.
